# Generated by Django 4.2.13 on 2024-06-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footfallapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footfallapp.video')),
            ],
        ),
    ]
