# Generated by Django 4.2.13 on 2024-06-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footfallapp', '0002_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(upload_to='output_videos/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footfallapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footfallapp.video')),
            ],
        ),
    ]
